### ISSUE TITLE
Running toflow on consecutive frames

### ISSUE THREAD

**Issue by Jamaslab** [anchen1011/toflow#18]
I would like to run your system inference on consecutive frames coming directly from the network, rather than on a stored video file on the disk. Is it possible? How would you suggest to do it?

**Comment by anchen1011** [comment]
The algorithm is processing videos frame-by-frame so it's definitely possible. You may want to modify the program so that:
frame i comes from the network -> store frame i on the disk -> run forward-pass to generate improved frame i-3 (or the frame between i and i-1 for interpolation) from frame i-6, frame frame i-5, frame i-4, frame i-3, frame i-2, frame i-1, frame i (or frame i-1, frame i for interpolation)
